### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by xnt** [xnt/react-something-nice#6]

**Comment by hugolesta** [comment]
Hello there, do you need help with this issue? I started a version with English as default language and Spanish as well. Tell me if I can contribute to your project.

**Comment by xnt** [comment]
¡Hola, Hugo! 

It'd be super cool if you could introduce localized files and a prop to choose one, for example. Thank you 🙏 !!

**Comment by hugolesta** [comment]
Hello xnt, nice to meet you. I performed the following code, so it works great but I'm not sure if you need develop using another technique.

`<SomethingNice lang ="es"/>`

The previous code switch to Spanish language. Let me know if these changes are good for your project or if you have additional ideas to solve this issue.

I've made one prop called lang as you can see in the previous example.

**Comment by xnt** [comment]
At a glance, looks great! I'd love it if you could introduce a PR, please. I'll check it out tomorrow morning.

**Comment by hugolesta** [comment]
Great, I'll introduce a PR in a new branch called languages. Thank you!

**Comment by hugolesta** [comment]
Hello xnt, I have introduced a new PR in a new branch called languages. Let me know if I may help you with anything else  

#14

**Comment by xnt** [comment]
Thank you, @hugolesta !
